export const cestas = [
  // {
  //   id: 1,
  //   nome: "Café Mimo de Mãe",
  //   preco: "170,00",
  //   imagem: "/cesta-mae.png",
  //   itens: [
  //     "Mini Bolo",
  //     "Sanduíche de Queijo e Presunto",
  //     "Pães de Queijo (60g)",
  //     "Torradinhas",
  //     "Biscoito Folheado",
  //     "Bolinhos de Tapioca (60g)",
  //     "Iogurte",
  //     "Suco Natural (200ml)",
  //     "Sachê de Cappuccino",
  //     "Geleia de Goiaba",
  //     "Cartinha Personalizada",
  //   ],
  // },
  // {
  //   id: 2,
  //   nome: "Para Compartilhar",
  //   preco: "385,00",
  //   imagem: "/cesta-mae2.png",
  //   itens: [
  //     "Mini Bolo",
  //     "6 Sanduíches de Queijo e Presunto",
  //     "Pães de Queijo (180g)",
  //     "Torradinhas",
  //     "Biscoitos Folheados",
  //     "Bolinhos de Tapioca (180g)",
  //     "3 Iogurtes",
  //     "3 Sucos Naturais (200ml)",
  //     "3 Sachês de Cappuccino",
  //     "Geleia de Goiaba",
  //     "Cartinha Personalizada",
  //   ],
  // },

  //----------------------------------------------------------------------//

  // {
  //   id: 1,
  //   nome: "Café Bom Dia com Amor",
  //   preco: "90,00",
  //   imagem: "/bom-dia.png",
  //   aceitaAdicionais: true,
  //   itens: [
  //     "Caixa Decorativa",
  //     "Cartinha Personalizada",
  //     "Arranjo de Balões",
  //     "2 Sanduíches de Queijo e Presunto",
  //     "Pão de Queijo (60g)",
  //     "Maçã Fresca",
  //     "Cookie",
  //     "Mamão",
  //     "Suco Natural (300ml)",
  //     "Mini Manteiga",
  //     "Sachê de Cappuccino",
  //   ],
  // },
  {
    id: 1,
    nome: "Café Especial Dia dos Namorados",
    preco: "169,90", // Formato Number para o carrinho calcular corretamente
    imagem: "/namorados.png", // Lembre de subir a foto com esse nome na pasta public
    aceitaAdicionais: "namorados",
    itens: [
      "Caixote Decorativo",
      "Balões Temáticos",
      "Bolo de Trigo (150g)",
      "Bolinhos de Tapioca",
      "Suco Natural (200ml)",
      "Torradinhas",
      "Minis Pães Delícia com Frango Cremoso",
      "Mini Geleia de Goiaba",
      "Sachê de Cappuccino",
      "Minis Croissants",
      "Polaroide com Foto do Casal",
    ],
  },
  {
    id: 2,
    nome: "Café Manhã dos Sonhos",
    preco: "220,00",
    imagem: "/sonhos.png",
    aceitaAdicionais: true,
    itens: [
      "Caixa Decorativa",
      "Cartinha Personalizada",
      "Balão Temático",
      "Pão de Queijo (60g)",
      "1 Croissant",
      "2 Pãezinhos com Doce de Leite",
      "2 Sanduíches de Queijo e Presunto",
      "Iogurte",
      "Bolo de Trigo",
      "Suco Natural (200ml)",
      "Chocolate Quente (200ml)",
      "Mini Manteiga",
      "Sachê de Cappuccino",
      "Torradas",
      "Kiwi",
      "Maçã",
      "Uvas",
    ],
  },
  // {
  //   id: 3,
  //   nome: "Café Light",
  //   preco: "150,00",
  //   imagem: "/ligth.png", // Imagem sugerida com frutas e visual leve
  //   aceitaAdicionais: true,
  //   itens: [
  //     "Caixa Decorativa",
  //     "Água de Coco",
  //     "Suco Natural (Sem Açúcar)",
  //     "Mamão com Chia",
  //     "Torradas",
  //     "Mini Manteiga",
  //     "2 Sanduíches Light",
  //     "Iogurte Zero Açúcar",
  //     "Uva",
  //     "Maçã",
  //     "Kiwi",
  //     "Sachê de Cappuccino",
  //   ],
  // },
  {
    id: 3,
    nome: "Cesta Kids",
    preco: "95,00",
    imagem: "/cesta-kids.png", // Imagem sugerida com frutas e visual leve
    aceitaAdicionais: "kids",
    itens: [
      "Balde de Pipoca",
      "Balões",
      "Nescau",
      "Danone",
      "Bolinho Bauduco",
      "Jujubas",
      "Kit Kat",
      "Fini",
      "Mini Brinquedo Surpresa (Menino/Menina)",
    ],
  },
];

export const ADICIONAIS = [
  { id: "ferrero", nome: "Ferreiro Rocher 3 unid", preco: 8.0 },
  { id: "suco", nome: "Suco natural 200ml", preco: 7.0 },
  { id: "sanduiche", nome: "Sanduíche de Queijo e Presunto", preco: 5.0 },
  { id: "croissant", nome: "Croissant", preco: 8.0 },
  { id: "barra", nome: "Barra de chocolate", preco: 12.0 },
  { id: "choc_quente", nome: "Chocolate Quente 300ml", preco: 9.9 },
  { id: "pao_queijo", nome: "Pães de queijo 60g", preco: 8.0 },
];

export const ADICIONAIS_KIDS = [{ id: 101, nome: "Balão Bubble", preco: 10.0 }];

export const ADICIONAIS_NAMORADOS = [
  { id: "suco", nome: "Suco natural 200ml", preco: 7.0 },
  { id: "pao_queijo", nome: "Pães de queijo 60g", preco: 8.0 },
];
