export const cestas = [
  {
    id: 1,
    nome: "Cesta Carinho e Sabor",
    preco: "185,00",
    imagem: "/carinho-sabor.png",
    itens: [
      "Mini Bolo",
      "Sanduíche de Queijo e Presunto",
      "Pães de Queijo (60g)",
      "Torradinhas",
      "Biscoito Folheado",
      "Bolinhos de Tapioca (60g)",
      "Iogurte",
      "Suco Natural (300ml)",
      "Sachê de Cappuccino",
      "Geleia de Goiaba",
      "Cartinha Personalizada",
    ],
  },
  {
    id: 2,
    nome: "Cesta Premium Família",
    preco: "385,00",
    imagem: "/premium-familia.png",
    itens: [
      "Mini Bolo",
      "6 Sanduíches de Queijo e Presunto",
      "Pães de Queijo (180g)",
      "Torradinhas",
      "Biscoitos Folheados",
      "Bolinhas de Tapioca (180g)",
      "3 Iogurtes",
      "3 Sucos Naturais (300ml)",
      "3 Sachês de Cappuccino",
      "Geleia de Goiaba",
      "Cartinha Personalizada",
    ],
  },
  // {
  //   id: 1,
  //   nome: "Café Bom Dia com Amor",
  //   preco: "80,00",
  //   imagem: "/bom-dia.png",
  //   itens: [
  //     "Caixa Decorativa",
  //     "Cartinha Personalizada",
  //     "Arranjo de Balões",
  //     "2 Sanduíches de Queijo e Presunto",
  //     "Pão de Queijo (60g)",
  //     "Maçã Fresca",
  //     "Uva",
  //     "Kiwi",
  //     "Suco Natural (300ml)",
  //     "Mini Manteiga",
  //     "Sachê de Cappuccino",
  //   ],
  // },
  // {
  //   id: 2,
  //   nome: "Café Manhã dos Sonhos",
  //   preco: "180,00",
  //   imagem: "/sonhos.png",
  //   itens: [
  //     "Caixa Decorativa",
  //     "Cartinha Personalizada",
  //     "Balão Temático",
  //     "Pão de Queijo (60g)",
  //     "1 Croissant",
  //     "2 Pãezinhos com Doce de Leite",
  //     "2 Sanduíches de Queijo e Presunto",
  //     "Iogurte",
  //     "Bolo de Trigo",
  //     "Suco Natural (300ml)",
  //     "Chocolate Quente (300ml)",
  //     "Mini Manteiga",
  //     "Sachê de Cappuccino",
  //     "Torradas",
  //     "Kiwi",
  //     "Maçã",
  //     "Uvas",
  //   ],
  // },
  // {
  //   id: 3,
  //   nome: "Café Light",
  //   preco: "150,00",
  //   imagem: "/ligth.png", // Imagem sugerida com frutas e visual leve
  //   itens: [
  //     "Água de Coco",
  //     "Suco Natural (Sem Açúcar)",
  //     "Mamão com Chia",
  //     "Torradas",
  //     "Mini Manteiga",
  //     "2 Sanduíches Light",
  //     "Iogurte Zero Açúcar",
  //     "Requeijão Light",
  //     "Uva",
  //     "Maçã",
  //     "Kiwi",
  //     "Sachê de Cappuccino",
  //   ],
  // },
];

export const ADICIONAIS = [
  // { id: "ferrero", nome: "Ferreiro Rocher 3 unid", preco: 8.0 },
  { id: "suco", nome: "Suco natural 300ml", preco: 7.0 },
  { id: "sanduiche", nome: "Sanduíche de Queijo e Presunto", preco: 5.0 },
  // { id: "croissant", nome: "Croissant", preco: 8.0 },
  // { id: "barra", nome: "Barra de chocolate", preco: 12.0 },
  { id: "choc_quente", nome: "Chocolate Quente 300ml", preco: 9.9 },
  { id: "pao_queijo", nome: "Pães de queijo 60g", preco: 8.0 },
];
